export { Home } from "./Home/Home";
export { SingleVideo } from "./SingleVideo/SingleVideo";
export { Liked } from "./LikedVideos/Liked";
export { WatchLater } from "./WatchLater/WatchLater";
export { History } from "./History/History";
export { Login } from "./Authentication/Login"
export { SignUp } from "./Authentication/Signup";
export { Playlists } from "./Playlists/Playlists";
export { Error } from "./404/404";